---
- name: Install python3-docker
  become: true
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Install Loki Docker logging driver plugin
  become: true
  community.docker.docker_plugin:
    plugin_name: "grafana/loki-docker-driver:{{ loki_driver_version }}"
    alias: loki
    state: present
