---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-boto3
    state: present
    update_cache: false

- name: Render docker-compose.yaml
  ansible.builtin.template:
    src: "docker-compose.{{ direction }}.yaml.j2"
    dest: /home/d.romashov/3x-ui/docker-compose.yaml
    owner: d.romashov
    group: wheel
    mode: "0644"

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: /home/d.romashov/3x-ui
    services:
      - 3xui
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: /home/d.romashov/3x-ui
    services:
      - 3xui
  register: output
