---
- name: Create lubelog working directory
  ansible.builtin.file:
    path: /opt/lubelog
    state: directory
    mode: '0750'

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/lubelog/docker-compose.yml
    mode: '0640'

- name: Fetch lubelog DB URL from Cloudflare KV
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/accounts/4faf2c3b5dd13669f97dd976498ad56a/storage/kv/namespaces/f0b474a7601c4e16bf88e3e290db5602/values/LUBELOG_DB_URL"
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
    return_content: true
    status_code: 200
  register: lubelog_db_url_result
  no_log: true

- name: Write .env file
  ansible.builtin.copy:
    content: "ConnectionStrings__LubeLoggerContext={{ lubelog_db_url_result.content }}\n"
    dest: /opt/lubelog/.env
    mode: '0600'
  no_log: true

- name: Remove any existing lubelog container
  community.docker.docker_container:
    name: lubelog
    state: absent

- name: Deploy lubelog
  community.docker.docker_compose_v2:
    project_src: /opt/lubelog
    pull: always
    recreate: always
    state: present

- name: Remove unused docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
