---
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to wheel group
    user:
      name=d.romashov
      groups=wheel
      append=yes
      state=present
      createhome=yes

  - name: Set up authorized keys for the deployer user
    authorized_key: user=d.romashov key="{{item}}"
    with_file:
      - ../files/komplukter.id_rsa.pub
      - ../files/pixel6.id_rsa.pub
      - ../files/workstation-Vostro-15-3510.id_rsa.pub
      - ../files/github_actions_id_rsa.pub

  - name: Set 'bash' as default shell for d.romashov user
    command: chsh -s /bin/bash d.romashov

  - name: Make sure we have a 'docker' group
    group:
      name: docker
      state: present

  - name: Add d.romshov user to 'docker' group
    user:
      name=d.romashov
      groups=docker
      append=yes
      state=present
      createhome=yes
