# ── A records ────────────────────────────────────────────────────────────────

resource "cloudflare_dns_record" "a_certs" {
  zone_id = local.zone_id
  name    = "4faf2c3b5dd13669f97dd976498ad56a"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_alloy" {
  zone_id = local.zone_id
  name    = "alloy"
  type    = "A"
  content = var.alloy_public_ip
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_dash" {
  zone_id = local.zone_id
  name    = "dash"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

# lube.romashov.tech → node2 (RU). Traefik reverse-proxies to ge node (91.239.206.123:18333).
resource "cloudflare_dns_record" "a_lube" {
  zone_id = local.zone_id
  name    = "lube"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_in_3x" {
  zone_id = local.zone_id
  name    = "in.3x"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_in" {
  zone_id = local.zone_id
  name    = "in"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 900
}

# status.romashov.tech → node2 (RU). Traefik reverse-proxies to Cloudflare Pages
# (static wrapper) and Grafana Cloud (dashboard paths). Direct DNS to Pages is
# avoided—many RU ISPs block *.pages.dev; see services/proxy/config/dynamic/status.yml.
resource "cloudflare_dns_record" "a_status" {
  zone_id = local.zone_id
  name    = "status"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_ge" {
  zone_id = local.zone_id
  name    = "ge"
  type    = "A"
  content = "188.120.235.164"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_node1" {
  zone_id = local.zone_id
  name    = "node1"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_node2" {
  zone_id = local.zone_id
  name    = "node2"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_node3" {
  zone_id = local.zone_id
  name    = "node3"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_node4" {
  zone_id = local.zone_id
  name    = "node4"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_out_3x" {
  zone_id = local.zone_id
  name    = "out.3x"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_out" {
  zone_id = local.zone_id
  name    = "out"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_russia" {
  zone_id = local.zone_id
  name    = "russia"
  type    = "A"
  content = "109.172.90.19"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "a_tg" {
  zone_id = local.zone_id
  name    = "tg"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_v2_tg" {
  zone_id = local.zone_id
  name    = "v2.tg"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_v3_tg" {
  zone_id = local.zone_id
  name    = "v3.tg"
  type    = "A"
  content = "144.124.231.157"
  proxied = false
  ttl     = 900
}

resource "cloudflare_dns_record" "a_vault" {
  zone_id = local.zone_id
  name    = "vault"
  type    = "A"
  content = "109.172.90.19"
  proxied = true
  ttl     = 1
}

resource "cloudflare_dns_record" "a_vpn" {
  zone_id = local.zone_id
  name    = "vpn"
  type    = "A"
  content = "206.168.215.160"
  proxied = false
  ttl     = 300
}

# dummy IP — redirected to Pages via proxied CNAME at apex
resource "cloudflare_dns_record" "a_www" {
  zone_id = local.zone_id
  name    = "www"
  type    = "A"
  content = "192.0.2.1"
  proxied = true
  ttl     = 1
}

# ── CNAME records ─────────────────────────────────────────────────────────────

# AAAA 100:: dummy records for api.foodikal and white-list-check-api are managed
# by Cloudflare Workers routing — read-only via DNS API (error 1043), not managed here.

# img.cartok CNAME → public.r2.dev is auto-generated by R2, read-only via DNS API (error 1052).

resource "cloudflare_dns_record" "cname_apex" {
  zone_id = local.zone_id
  name    = "romashov.tech"
  type    = "CNAME"
  content = "romashov-tech-web.pages.dev"
  proxied = true
  ttl     = 1
}

resource "cloudflare_dns_record" "cname_webhook" {
  zone_id = local.zone_id
  name    = "webhook"
  type    = "CNAME"
  content = "66ff916b-882e-431a-80dc-f89db5e3e3b0.cfargotunnel.com"
  proxied = true
  ttl     = 1
}

# ── MX records ────────────────────────────────────────────────────────────────

resource "cloudflare_dns_record" "mx_apex" {
  zone_id  = local.zone_id
  name     = "romashov.tech"
  type     = "MX"
  content  = "mx.yandex.net"
  priority = 10
  proxied  = false
  ttl      = 1
}

# ── TXT records ───────────────────────────────────────────────────────────────

resource "cloudflare_dns_record" "txt_acme_challenge_m_inventory" {
  zone_id = local.zone_id
  name    = "_acme-challenge.m.inventory"
  type    = "TXT"
  content = "gr5QNpe1jg2tKcukt95dNC-uptmtSeiXzuwpWH5fEJw"
  proxied = false
  ttl     = 120
}

resource "cloudflare_dns_record" "txt_mail_dkim" {
  zone_id = local.zone_id
  name    = "mail._domainkey"
  type    = "TXT"
  content = "v=DKIM1; k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbSNNEHtWeRj/cs5JPgi2QmPu9mHDeQwOVANihaITDjCq8Q4JNtPhoMzUxllY5wTYO776BFRU7+gEfXu0kM3GUamPmQetcA/xQCmWoCHhxjEltifCPDavDKS+bZNuuL6brDaXAV4xl1SB4qjbCAt5YmIl3V8rBcwjUhr+c8awctQIDAQAB"
  proxied = false
  ttl     = 1
}

resource "cloudflare_dns_record" "txt_apex_spf" {
  zone_id = local.zone_id
  name    = "romashov.tech"
  type    = "TXT"
  content = "v=spf1 redirect=_spf.yandex.net"
  proxied = false
  ttl     = 1
}
