---
- hosts: _3xui
  become: true
  become_user: d.romashov
  vars:
    application: "3x-ui-{{ direction }}"
    project_path: "/home/d.romashov/romashov-tech"
  roles:
    - romashov-tech-deployment
