---
- hosts: 3x-ui-in
  become: true
  become_user: d.romashov
  vars:
    direction: "in"
  roles:
    - 3x-ui
- hosts: 3x-ui-out
  become: true
  become_user: d.romashov
  vars:
    direction: "out"
  roles:
    - 3x-ui
