---
- hosts: all
  vars:
    apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    filebeat_version: 7.10.2
    filebeat_create_config: false
  roles:
  - basic
  - create-users
  - ansible-role-docker
  # - filebeat
  post_tasks:
    - name: Check if Loki Docker logging driver plugin is installed
      become: true
      ansible.builtin.command: docker plugin inspect loki
      register: loki_plugin_check
      failed_when: false
      changed_when: false
    - name: Install Loki Docker logging driver plugin
      become: true
      ansible.builtin.command: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
      when: loki_plugin_check.rc != 0
