---
- hosts: _3xui
  become: true
  become_user: d.romashov
  vars:
    application: 3xui
    project_path: "/home/d.romashov/romashov-tech"
  tasks:
    - name: Run restore tasks from 3x-ui role
      ansible.builtin.include_role:
        name: 3x-ui
        tasks_from: restore.yml
