---
  - name: Check if Speedtest is installed
    command: dpkg-query -W speedtest
    register: speedtest_check_deb
    failed_when: speedtest_check_deb.rc > 1
    changed_when: speedtest_check_deb.rc == 1

  - name: Download Speedtest deb package
    shell: "wget --content-disposition 'https://packagecloud.io/ookla/speedtest-cli/packages/ubuntu/jammy/{{ package_name }}/download.deb?distro_version_id=237'"
    args:
      chdir: /tmp
    when: speedtest_check_deb.rc == 1

  - name: Install Speedtest
    apt:
      deb: "/tmp/{{ package_name }}"
    when: speedtest_check_deb.rc == 1

  - name: Remove deb package
    file:
      path: "/tmp/{{ package_name }}"
      state: absent
    when: speedtest_check_deb.rc == 1

  - name: Check if Openconnect is installed
    command: dpkg-query -W openconnect
    register: openconnect_check_deb
    failed_when: openconnect_check_deb.rc > 1
    changed_when: openconnect_check_deb.rc == 1

  - name: Installing Openconnect
    apt:
      name: openconnect
      update_cache: yes
    when: openconnect_check_deb.rc == 1

  - name: Uninstall previous version of cron job
    command: ./esst.sh uninstall
    args:
      chdir: "{{ project_path }}/tests/speed/es_speedtest_cli/"
      removes: /opt/esst
      
  - name: Install new version of cron job
    command: ./esst.sh install
    args:
      chdir: "{{ project_path }}/tests/speed/es_speedtest_cli/"
      creates: /opt/esst
