---
  - name: Check if speedtest is installed
    command: dpkg-query -W speedtest
    register: speedtest_check_deb
    failed_when: speedtest_check_deb.rc > 1
    changed_when: speedtest_check_deb.rc == 1

  - name: Download speedtest deb package
    shell: "wget --content-disposition 'https://packagecloud.io/ookla/speedtest-cli/packages/ubuntu/jammy/{{ package_name }}/download.deb?distro_version_id=237'"
    args:
      chdir: /tmp
    when: speedtest_check_deb.rc == 1

  - name: Install speedtest
    apt:
      deb: "/tmp/{{ package_name }}"
    when: speedtest_check_deb.rc == 1

  - name: Remove deb package
    file:
      path: "/tmp/{{ package_name }}"
      state: absent
    when: speedtest_check_deb.rc == 1
