---
  - name: Set up ssh key for git
    copy:
      src: ../files/ssh-config
      dest: /home/d.romashov/.ssh/config
      owner: d.romashov
      group: wheel
      mode: 0644
      force: no

  - name: Check if romashov-tech repo exists
    stat:
      path: /home/d.romashov/romashov-tech
    register: repo_exists_check

  - name: Clone romashov-tech repo
    ansible.builtin.git:
      repo: git@github.com:framebassman/romashov-tech.git
      dest: /home/d.romashov/romashov-tech
      single_branch: no
      version: master
      accept_hostkey: yes
    when: not repo_exists_check.stat.exists

  - name: Reset all changes
    ansible.builtin.git:
      repo: git@github.com:framebassman/romashov-tech.git
      dest: /home/d.romashov/romashov-tech
      version: master
      update: yes
      force: yes
      clone: no
      single_branch: no
      accept_hostkey: yes

  - name: Stop Deployment
    shell: "make stop-prod-{{ application }}"
    args:
      chdir: /home/d.romashov/romashov-tech

  - name: Start Deployment
    shell: "make start-prod-{{ application }}"
    args:
      chdir: /home/d.romashov/romashov-tech

  - name: Cleanup docker images
    shell: make docker-cleanup -i
    args:
      chdir: /home/d.romashov/romashov-tech

  - name: Remove unused docker images
    shell: docker image prune --all --force
