---
  - name: Installing additional software
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - git
      - vim
      - curl
      - mc
      - make

  - name: Adding bashrc
    copy: src=../files/bash.bashrc dest=/etc/bash.bashrc
          owner=root group=root mode=0644

  - name: Removing standard bashrc
    shell: creates=/root/.bashrc_backup mv /root/.bashrc /root/.bashrc_backup

  - name: Check fqdn is set for this host
    ansible.builtin.assert:
      that:
        - fqdn is defined
        - (fqdn | string | length) > 0
      fail_msg: "Задайте fqdn для хоста в инвентаре."

  - name: Set system hostname
    ansible.builtin.hostname:
      name: "{{ fqdn }}"
    become_user: root

  - name: Get public IP
    uri:
      url: https://api.ipify.org
      return_content: yes
    register: public_ip

  - name: Populate PUBLIC_IP environment variable
    lineinfile:
      path: "/etc/environment"
      state: present
      regexp: "^PUBLIC_IP="
      line: "PUBLIC_IP={{ public_ip.content }}"
    become: yes

  - name: Ensure CLOUDFLARE_API_TOKEN exists locally
    fail:
      msg: "CLOUDFLARE_API_TOKEN is not set"
    when: CLOUDFLARE_API_TOKEN is not defined or CLOUDFLARE_API_TOKEN == ''

  - name: Populate CLOUDFLARE_API_TOKEN environment variable
    lineinfile:
      path: "/etc/environment"
      regexp: "^CLOUDFLARE_API_TOKEN="
      line: "CLOUDFLARE_API_TOKEN={{ CLOUDFLARE_API_TOKEN }}"
      state: present
    become: yes

  - name: Install AWS SDK dependencies
    ansible.builtin.apt:
      name:
        - python3-boto3
      state: present
      update_cache: yes
    when: "'vpn' in group_names or '_3xui' in group_names"
