russian:
  hosts:
    109.172.90.19:
      fqdn: node2.romashov.tech
sweden:
  hosts:
    79.76.47.245:
      fqdn: alloy.romashov.tech
      ansible_user: ubuntu
      ansible_become: yes
      ansible_become_method: sudo
georgia:
  hosts:
    188.120.235.164:
      fqdn: ge.romashov.tech
vpn:
  hosts:
    109.172.90.19:
    185.121.233.152:
      fqdn: node1.romashov.tech
mtproxy:
  hosts:
    185.121.233.152:
