---
- hosts: all
  vars:
    apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    filebeat_version: 7.10.2
    filebeat_create_config: false
  roles:
  - basic
  - create-users
  - ansible-role-docker
  # - filebeat

- hosts: russia
  vars:
    package_name: "speedtest_1.2.0.84-1.ea6b6773cf_amd64.deb"
  roles:
  - speedtest
