---
- hosts: all
  become: true
  vars:
    docker_edition: 'ce'
    docker_install_compose: true
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_compose_version: 'v2.15.1'
    docker_compose_arch: aarch64
    docker_compose_path: /usr/local/bin/docker-compose
  roles:
  - basic
  - ansible-role-docker
  - create_users
