---
- hosts: all
  become: true
  vars:
    apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    docker_apt_release_channel: stable
    docker_apt_arch: "{{ apt_arch }}"
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: True
    docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
    docker_apt_filename: "docker"
    docker_edition: 'ce'
    docker_install_compose: true
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_compose_version: 'v2.21.0'
    docker_compose_arch: "{{ ansible_architecture }}"
    docker_compose_path: /usr/local/bin/docker-compose
    filebeat_version: 7.10.2
    filebeat_create_config: false
  roles:
  - basic
  # - ansible-role-docker
  - filebeat
  - create_users
