services:
  lubelog:
    image: ghcr.io/hargata/lubelog:v1.6.7
    container_name: lubelog
    ports:
      - "8000:8080"
    env_file:
      - .env
    volumes:
      - lubelog_data:/App/data
    restart: unless-stopped

volumes:
  lubelog_data:
    name: lubelog_data
