name: Deploy infrastructure to production
on:
  pull_request:
    branches:
      - 'master'
jobs:
  apply-terraform-modules:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: terraform
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Populate secrets
        run: |
          echo $BACKEND_CONF_BASE64 | base64 --decode > backend.conf
        env:
          BACKEND_CONF_BASE64: ${{ secrets.BACKEND_CONF_BASE64 }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.6"
      - run: terraform init -backend-config=backend.conf
      - run: terraform plan -lock-timeout=5m
      - run: terraform apply -auto-approve -lock-timeout=5m

  apply-infrastructure-playbook:
    runs-on: ubuntu-24.04
    needs: apply-terraform-modules
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run infrastructure playbook
        uses: dawidd6/action-ansible-playbook@v9
        with:
            # Optional, directory where playbooks live
          directory: ./ansible
          # Required, playbook filepath
          playbook: ./playbooks/infrastructure.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, galaxy requirements filepath
          requirements: ./requirements.yml
          options: |
            --extra-vars CLOUDFLARE_API_TOKEN=${{secrets.CLOUDFLARE_API_TOKEN}}
      - name: Run firewall playbook for VPN nodes
        uses: dawidd6/action-ansible-playbook@v9
        with:
            # Optional, directory where playbooks live
          directory: ./ansible
          # Required, playbook filepath
          playbook: ./playbooks/vpn-firewall.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, galaxy requirements filepath
          requirements: ./requirements.yml
