name: Cleanup old indexes
on: [push]
jobs:
  Cleanup-old-indexes:
    runs-on: ubuntu-22.04
    steps:
      - name: Cleanup indexes more than 4 days
        run: |
          curl --location
            --request POST
            'https://$USERNAME:$PASSWORD@kolenka-inc-4135333449.eu-central-1.bonsaisearch.net/filebeat-7.10.2-2023.02.02/_delete_by_query' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "query": {
                "match_all": {}
              }
            }'
        env:
          USERNAME: fmtucerc0m
          PASSWORD: g1zbfbj8ly
        shell: bash
