on:
  push:
    branches:
      - master
    paths:
      - ansible/roles/lubelog/**
      - ansible/playbooks/deploy-lubelog.yml
      - .github/workflows/lubelog-deploy.yml
  workflow_dispatch:

name: lubelog-deploy

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy lubelog
        uses: dawidd6/action-ansible-playbook@v9
        with:
          directory: ./ansible
          playbook: ./playbooks/deploy-lubelog.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          requirements: requirements.yml
          options: |
            --extra-vars "cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
