name: VPN firewall rollback (iptables DOCKER-USER)

on:
  workflow_dispatch:

jobs:
  rollback-vpn-firewall:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run vpn-firewall-rollback playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          directory: ./ansible
          playbook: ./playbooks/vpn-firewall-rollback.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          requirements: ./requirements.yml
